from .benchmark import WebMallBenchmark
import numpy as np
from browsergym.experiments.benchmark.configs import DEFAULT_HIGHLEVEL_ACTION_SET_ARGS
from .utils import make_env_args_list_from_repeat_tasks
from browsergym.experiments.benchmark.metadata.utils import task_metadata, task_list_from_metadata

WEBMALL_BENCHMARKS = {
    "webmall_v0.7": lambda: WebMallBenchmark(
        name="webmall_v0.7",
        high_level_action_set_args=DEFAULT_HIGHLEVEL_ACTION_SET_ARGS["webarena"],
        is_multi_tab=True,
        supports_parallel_seeds=True,
        backends=["webmall"],
        env_args_list=make_env_args_list_from_repeat_tasks(
            task_list=task_list_from_metadata(metadata=task_metadata("webmall")),
            max_steps=50,
            n_repeats=1,
            seeds_rng=np.random.RandomState(42),
        ),
        task_metadata=task_metadata("webmall"),
    ),
    "webmall_j_v0.7": lambda: WebMallBenchmark(
        name="webmall_j_v0.7",
        high_level_action_set_args=DEFAULT_HIGHLEVEL_ACTION_SET_ARGS["webarena"],
        is_multi_tab=True,
        supports_parallel_seeds=True,
        backends=["webmall"],
        env_args_list=make_env_args_list_from_repeat_tasks(
            task_list=[
                       "webmall.Webmall_Checkout_Task1", "webmall.Webmall_Checkout_Task2", 
                       "webmall.Webmall_Checkout_Task3", "webmall.Webmall_Checkout_Task4", 
                       "webmall.Webmall_Checkout_Task5", "webmall.Webmall_Checkout_Task6", 
                       "webmall.Webmall_Checkout_Task7", "webmall.Webmall_Checkout_Task8"
                       ],
            max_steps=50,
            n_repeats=1,
            seeds_rng=np.random.RandomState(42),
        ),
        task_metadata=task_metadata("webmall"),
    ),
    "webmall_basic_v0.7": lambda: WebMallBenchmark(
        name="webmall_basic_v0.7",
        high_level_action_set_args=DEFAULT_HIGHLEVEL_ACTION_SET_ARGS["webarena"],
        is_multi_tab=True,
        supports_parallel_seeds=True,
        backends=["webmall"],
        env_args_list=make_env_args_list_from_repeat_tasks(
            task_list=["webmall.Webmall_Single_Product_Search_Task1", "webmall.Webmall_Single_Product_Search_Task2", 
                       "webmall.Webmall_Single_Product_Search_Task3", "webmall.Webmall_Single_Product_Search_Task4", 
                       "webmall.Webmall_Single_Product_Search_Task5", "webmall.Webmall_Single_Product_Search_Task6", 
                       "webmall.Webmall_Single_Product_Search_Task7", "webmall.Webmall_Single_Product_Search_Task8", 
                       "webmall.Webmall_Single_Product_Search_Task9", "webmall.Webmall_Single_Product_Search_Task10", 
                       "webmall.Webmall_Single_Product_Search_Task11", "webmall.Webmall_Single_Product_Search_Task12", 
                       "webmall.Webmall_Cheapest_Product_Search_Task1", "webmall.Webmall_Cheapest_Product_Search_Task2", 
                       "webmall.Webmall_Cheapest_Product_Search_Task3", "webmall.Webmall_Cheapest_Product_Search_Task4", 
                       "webmall.Webmall_Cheapest_Product_Search_Task5", "webmall.Webmall_Cheapest_Product_Search_Task6", 
                       "webmall.Webmall_Cheapest_Product_Search_Task7", "webmall.Webmall_Cheapest_Product_Search_Task8", 
                       "webmall.Webmall_Cheapest_Product_Search_Task9", "webmall.Webmall_Cheapest_Product_Search_Task10",
                       "webmall.Webmall_Best_Fit_Specific_Task1", "webmall.Webmall_Best_Fit_Specific_Task2", 
                       "webmall.Webmall_Best_Fit_Specific_Task3", "webmall.Webmall_Best_Fit_Specific_Task4", 
                       "webmall.Webmall_Best_Fit_Specific_Task5", "webmall.Webmall_Best_Fit_Specific_Task6", 
                       "webmall.Webmall_Best_Fit_Specific_Task7", "webmall.Webmall_Best_Fit_Specific_Task8", 
                       "webmall.Webmall_Best_Fit_Specific_Task9", "webmall.Webmall_Best_Fit_Specific_Task10", 
                       "webmall.Webmall_Best_Fit_Specific_Task11", 
                       "webmall.Webmall_Add_To_Cart_Task1", "webmall.Webmall_Add_To_Cart_Task2", 
                       "webmall.Webmall_Add_To_Cart_Task3", "webmall.Webmall_Add_To_Cart_Task4", 
                       "webmall.Webmall_Add_To_Cart_Task5", "webmall.Webmall_Add_To_Cart_Task6", 
                       "webmall.Webmall_Add_To_Cart_Task7", 
                       "webmall.Webmall_Checkout_Task1", "webmall.Webmall_Checkout_Task2", 
                       "webmall.Webmall_Checkout_Task3", "webmall.Webmall_Checkout_Task4", 
                       "webmall.Webmall_Checkout_Task5", "webmall.Webmall_Checkout_Task6", 
                       "webmall.Webmall_Checkout_Task7", "webmall.Webmall_Checkout_Task8"
                       ],
            max_steps=50,
            n_repeats=1,
            seeds_rng=np.random.RandomState(42),
        ),
        task_metadata=task_metadata("webmall"),
    ),
    "webmall_advanced_v0.7": lambda: WebMallBenchmark(
        name="webmall_advanced_v0.7",
        high_level_action_set_args=DEFAULT_HIGHLEVEL_ACTION_SET_ARGS["webarena"],
        is_multi_tab=True,
        supports_parallel_seeds=True,
        backends=["webmall"],
        env_args_list=make_env_args_list_from_repeat_tasks(
            task_list=["webmall.Webmall_Find_Compatible_Products_Task1", "webmall.Webmall_Find_Compatible_Products_Task2", 
                       "webmall.Webmall_Find_Compatible_Products_Task3", "webmall.Webmall_Find_Compatible_Products_Task4", 
                       "webmall.Webmall_Find_Compatible_Products_Task5", 
                       "webmall.Webmall_Best_Fit_Vague_Task1", "webmall.Webmall_Best_Fit_Vague_Task2", 
                       "webmall.Webmall_Best_Fit_Vague_Task3", "webmall.Webmall_Best_Fit_Vague_Task4", 
                       "webmall.Webmall_Best_Fit_Vague_Task5", "webmall.Webmall_Best_Fit_Vague_Task6", 
                       "webmall.Webmall_Best_Fit_Vague_Task7", "webmall.Webmall_Best_Fit_Vague_Task9", 
                       "webmall.Webmall_Cheapest_Best_Fit_Specific_Task1", "webmall.Webmall_Cheapest_Best_Fit_Specific_Task2", 
                       "webmall.Webmall_Cheapest_Best_Fit_Specific_Task3", "webmall.Webmall_Cheapest_Best_Fit_Specific_Task4", 
                       "webmall.Webmall_Cheapest_Best_Fit_Specific_Task5", "webmall.Webmall_Cheapest_Best_Fit_Specific_Task6", 
                       "webmall.Webmall_Cheapest_Best_Fit_Specific_Task7", "webmall.Webmall_Cheapest_Best_Fit_Specific_Task8", 
                       "webmall.Webmall_Cheapest_Best_Fit_Specific_Task9", "webmall.Webmall_Cheapest_Best_Fit_Specific_Task10", 
                       "webmall.Webmall_Cheapest_Best_Fit_Vague_Task1", "webmall.Webmall_Cheapest_Best_Fit_Vague_Task2", 
                       "webmall.Webmall_Cheapest_Best_Fit_Vague_Task3", "webmall.Webmall_Cheapest_Best_Fit_Vague_Task4", 
                       "webmall.Webmall_Cheapest_Best_Fit_Vague_Task5", "webmall.Webmall_Cheapest_Best_Fit_Vague_Task6", 
                       "webmall.Webmall_Substitutes_Task1", "webmall.Webmall_Substitutes_Task2", 
                       "webmall.Webmall_Substitutes_Task3", "webmall.Webmall_Substitutes_Task4", 
                       "webmall.Webmall_Substitutes_Task5", "webmall.Webmall_Substitutes_Task6"],
            max_steps=50,
            n_repeats=1,
            seeds_rng=np.random.RandomState(42),
        ),
        task_metadata=task_metadata("webmall"),
    ),
    "webmall_tiny_v0.7": lambda: WebMallBenchmark(
        name="webmall_tiny_v0.7",
        high_level_action_set_args=DEFAULT_HIGHLEVEL_ACTION_SET_ARGS["webarena"],
        is_multi_tab=True,
        supports_parallel_seeds=True,
        backends=["webmall"],
        env_args_list=make_env_args_list_from_repeat_tasks(
            task_list=["webmall.Webmall_Single_Product_Search_Task4", "webmall.Webmall_Single_Product_Search_Task5",
                        "webmall.Webmall_Cheapest_Product_Search_Task4", "webmall.Webmall_Cheapest_Product_Search_Task5",
                        "webmall.Webmall_Best_Fit_Specific_Task4", "webmall.Webmall_Best_Fit_Specific_Task5",
                        "webmall.Webmall_Best_Fit_Vague_Task4", "webmall.Webmall_Best_Fit_Vague_Task5",
                        "webmall.Webmall_Cheapest_Best_Fit_Specific_Task4", "webmall.Webmall_Cheapest_Best_Fit_Specific_Task5",
                        "webmall.Webmall_Cheapest_Best_Fit_Vague_Task4", "webmall.Webmall_Cheapest_Best_Fit_Vague_Task5",
                        "webmall.Webmall_Add_To_Cart_Task4", "webmall.Webmall_Add_To_Cart_Task5",
                        "webmall.Webmall_Find_Compatible_Products_Task4", "webmall.Webmall_Find_Compatible_Products_Task5",
                        "webmall.Webmall_Substitutes_Task4", "webmall.Webmall_Substitutes_Task5",
                        "webmall.Webmall_Checkout_Task4", "webmall.Webmall_Checkout_Task5",],
            max_steps=50,
            n_repeats=1,
            seeds_rng=np.random.RandomState(42),
        ),
        task_metadata=task_metadata("webmall"))}